### ISSUE TITLE
Setting transparent background

### ISSUE THREAD

**Issue by theoklink** [maxmpz/powerampapi#18]
Different behaviours:
to set background to transparent, using 2 approaches

**com.maxmpz.audioplayer:ItemRatingBar_scene_aa**;  
`<item name="com.maxmpz.audioplayer:lineBackground">@color/transparent </item>`
result PASS

**com.maxmpz.audioplayer:ItemLikeUnlikeLayout_scene_aa**;
`<item name="com.maxmpz.audioplayer:lineBackground">@color/transparent </item>`
result FAIL

**com.maxmpz.audioplayer:ItemTrackMenu_scene_aa**;
`<item name="com.maxmpz.audioplayer:lineBackground">@color/transparent </item>`
result FAIL

**com.maxmpz.audioplayer:ItemTrackMenu**;
`<item name="com.maxmpz.audioplayer:lineBackground">@color/transparent </item>`
result FAIL

and

**com.maxmpz.audioplayer:ItemRatingBar_scene_aa**;  
`<item name="android:background"">@color/transparent</item>`
result FAIL

**com.maxmpz.audioplayer:ItemLikeUnlikeLayout_scene_aa**;
`<item name="android:background"">@color/transparent</item>`
result FAIL

**com.maxmpz.audioplayer:ItemTrackMenu_scene_aa**;
`<item name="android:background"">@color/transparent</item>`
result FAIL

**com.maxmpz.audioplayer:ItemTrackMenu**;
`<item name="android:background"">@color/transparent</item>`
result PASS

Conclusion:
end result is that I am able to achieve transparent backgound for 2 icons, although using different approaches and on different objects (_scene_aa and ItemTrackMenu)
Trying to set transparent background for ItemLikeUnlikeLayout_scene_aa does not work with either approach
As a general observation, the use of com.maxmpz.audioplayer:lineBackground and android:background does not appear to follow consistent rules to what in my view are similar objects

**Comment by maxmpz** [comment]
Can you please specify, first, what is the target of such background?
Something in menu? Or 

lineBackground is usually for text, not for other components, except some very specific ones (like meta), this is separate, non-Android drawn background. It can be animated between scenes.

Usual background can be also animated for limited set of views (basically FastTextView and FastButtons and derived classes).

Transparent color is color with value == 0 (#0000 == #00000000). This one have special value as it specifies "no-change for animation" for 

This is required as lower Androids (e.g. 5) can't properly store/parse @empty / @null in colors, thus, some color need to be specified as "no-change" color. 

As I can see this is documented in internal code only, documentation is not exposed yet to published xmls - I'll add that.

**Comment by maxmpz** [comment]
So based on #0000 (or color/transparent) as a "no-change" color for any *scene* style, you may want to change:
- base style for views which define background / lineBackground. If other scenes should have same (transparent) background, the best way is to set background / lineBackground  to @null for them or to #0000. Otherwise set to appropriate color / drawable

- background vs lineBackground
  - background is just Android background, which has always rectangular bounds (can be rounded rectangle, but bounds are rectangle). Used for buttons.

  - lineBackground for FastText wrapping background, it wraps text so each line gets own background shape / rectangle. Used only for text labels.

 - lineBackground for few selected components (BgTransView derived, currently RatingBar, FitsNavigationBarView and FitsStatusBarView). Animated background - animates when content changes inside. Required as standard Android background can't be animated this way.

**Comment by theoklink** [comment]
thank you for the response

>  Can you please specify, first, what is the target of such background?

I am trying to set the background of the menu, rating, like/unlike to transparent

**Comment by maxmpz** [comment]
Ok, please start overriding then base styles (not the ones with the _scene* suffix).

Re: _scene* styles - see my comment above for #0000 "no-change" color.
